import { CarListing, AuctionListing } from '@/types';

export const MAKES = [
  'Alfa Romeo', 'Aston Martin', 'Auburn', 'Bentley', 'Bugatti',
  'Buick', 'Cadillac', 'Chevrolet', 'Chrysler', 'Cord',
  'Duesenberg', 'Ferrari', 'Ford', 'Hudson', 'Jaguar',
  'Lamborghini', 'Lincoln', 'Lotus', 'Maserati', 'Mercedes-Benz',
  'MG', 'Nash', 'Oldsmobile', 'Packard', 'Pierce-Arrow',
  'Plymouth', 'Pontiac', 'Porsche', 'Rolls-Royce', 'Studebaker',
  'Triumph', 'Tucker', 'Volkswagen', 'Willys'
];

export const COLORS = [
  'Black', 'White', 'Silver', 'Red', 'Blue', 'Green',
  'Yellow', 'Gold', 'Brown', 'Burgundy', 'Cream', 'Gray',
  'Orange', 'Purple', 'Turquoise', 'Two-Tone', 'Other'
];

export const FEATURES = [
  'Original Paint', 'Matching Numbers', 'Full Frame-Off Restoration',
  'Numbers Matching Engine', 'Original Interior', 'Air Conditioning',
  'Power Steering', 'Power Brakes', 'Overdrive Transmission',
  'Power Windows', 'Factory Radio', 'Chrome Bumpers',
  'Whitewall Tires', 'Wire Wheels', 'Spoke Wheels',
  'Convertible Top', 'Rumble Seat', 'Dual Carbs',
  'Supercharged', 'Dual Exhaust', 'Positraction',
  'Floor Shift', 'Bucket Seats', 'Console',
  'Show Car', 'Award Winner', 'Documented History'
];

const now = new Date();

export const SAMPLE_CARS: CarListing[] = [
  {
    id: 'car1',
    sellerId: 'user1',
    sellerName: 'Robert Harrington',
    title: '1957 Chevrolet Bel Air - Frame-Off Restored',
    make: 'Chevrolet',
    model: 'Bel Air',
    year: 1957,
    price: 85000,
    mileage: 47200,
    condition: 'Restored',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    bodyStyle: 'Sedan',
    driveType: 'RWD',
    color: 'Two-Tone',
    interiorColor: 'Red',
    engine: '283 V8',
    horsepower: 270,
    doors: 4,
    vin: 'VC57BE12345',
    location: 'Nashville, TN',
    description: 'Stunning frame-off restoration of this iconic 1957 Chevrolet Bel Air. Matching numbers, original color combination restored to factory specs. Trophy winner at multiple concours events.',
    features: ['Matching Numbers', 'Full Frame-Off Restoration', 'Original Paint', 'Chrome Bumpers', 'Whitewall Tires', 'Award Winner'],
    images: ['https://images.unsplash.com/photo-1567808291548-fc3ee04dbcf0?w=800&q=80'],
    createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    isAuction: false,
  },
  {
    id: 'car2',
    sellerId: 'user2',
    sellerName: 'Margaret Collins',
    title: '1969 Ford Mustang Fastback 428 Cobra Jet',
    make: 'Ford',
    model: 'Mustang',
    year: 1969,
    price: 125000,
    mileage: 34500,
    condition: 'Excellent',
    fuelType: 'Gasoline',
    transmission: 'Manual',
    bodyStyle: 'Coupe',
    driveType: 'RWD',
    color: 'Black',
    interiorColor: 'Black',
    engine: '428 Cobra Jet V8',
    horsepower: 335,
    doors: 2,
    vin: 'VC69MU67890',
    location: 'Detroit, MI',
    description: 'Numbers matching 428 Cobra Jet Fastback. One of the most sought-after muscle cars. Original black on black configuration with factory Marti report documentation.',
    features: ['Matching Numbers', 'Numbers Matching Engine', 'Documented History', 'Floor Shift', 'Bucket Seats'],
    images: ['https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80'],
    createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    isAuction: false,
  },
  {
    id: 'car3',
    sellerId: 'user3',
    sellerName: 'James Whitfield',
    title: '1965 Shelby Cobra 427 - Authentic CSX',
    make: 'Ford',
    model: 'Shelby Cobra',
    year: 1965,
    price: 950000,
    mileage: 12000,
    condition: 'Excellent',
    fuelType: 'Gasoline',
    transmission: 'Manual',
    bodyStyle: 'Roadster',
    driveType: 'RWD',
    color: 'Blue',
    interiorColor: 'Black',
    engine: '427 FE V8',
    horsepower: 425,
    doors: 2,
    vin: 'CSX3001',
    location: 'Los Angeles, CA',
    description: 'One of the most valuable American sports cars ever produced. Authenticated CSX serial number with complete documentation. Race history documented.',
    features: ['Matching Numbers', 'Documented History', 'Original Interior', 'Dual Carbs', 'Dual Exhaust'],
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80'],
    createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    isAuction: false,
  },
  {
    id: 'car4',
    sellerId: 'user4',
    sellerName: 'Eleanor Vance',
    title: '1970 Dodge Challenger R/T 440 Six Pack',
    make: 'Dodge',
    model: 'Challenger',
    year: 1970,
    price: 175000,
    mileage: 28900,
    condition: 'Excellent',
    fuelType: 'Gasoline',
    transmission: 'Manual',
    bodyStyle: 'Coupe',
    driveType: 'RWD',
    color: 'Orange',
    interiorColor: 'Black',
    engine: '440 Six Pack V8',
    horsepower: 390,
    doors: 2,
    vin: 'VC70CH44444',
    location: 'Phoenix, AZ',
    description: 'Matching numbers 440 Six Pack Challenger R/T in Hemi Orange. One of the most iconic muscle cars of the golden era. Excellent driver quality with investment potential.',
    features: ['Matching Numbers', 'Numbers Matching Engine', 'Positraction', 'Floor Shift', 'Bucket Seats'],
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80'],
    createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isAuction: false,
  },
  {
    id: 'car5',
    sellerId: 'user5',
    sellerName: 'Harold Pennington',
    title: '1932 Ford Deuce Coupe - Original Highboy',
    make: 'Ford',
    model: 'Model B',
    year: 1932,
    price: 62000,
    mileage: 55000,
    condition: 'Good',
    fuelType: 'Gasoline',
    transmission: 'Manual',
    bodyStyle: 'Coupe',
    driveType: 'RWD',
    color: 'Black',
    interiorColor: 'Brown',
    engine: 'Flathead V8',
    horsepower: 110,
    doors: 2,
    vin: 'VC32FD11111',
    location: 'Sacramento, CA',
    description: 'Legendary 1932 Ford Deuce Coupe in traditional highboy style. Flathead V8 with period-correct equipment. Classic hot rod heritage with documented history.',
    features: ['Original Interior', 'Documented History', 'Chrome Bumpers'],
    images: ['https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?w=800&q=80'],
    createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    isAuction: false,
  },
  {
    id: 'car6',
    sellerId: 'user6',
    sellerName: 'Victoria Sterling',
    title: '1963 Ferrari 250 GT Lusso',
    make: 'Ferrari',
    model: '250 GT Lusso',
    year: 1963,
    price: 2800000,
    mileage: 19500,
    condition: 'Excellent',
    fuelType: 'Gasoline',
    transmission: 'Manual',
    bodyStyle: 'Coupe',
    driveType: 'RWD',
    color: 'Red',
    interiorColor: 'Tan',
    engine: 'Colombo V12',
    horsepower: 250,
    doors: 2,
    vin: 'VC63FE25000',
    location: 'Monterey, CA',
    description: 'One of the most beautiful Ferraris ever built. This Pininfarina-bodied GT has been in a single collection for decades. Complete with Classiche certification.',
    features: ['Matching Numbers', 'Documented History', 'Original Interior', 'Award Winner', 'Show Car'],
    images: ['https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=800&q=80'],
    createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isAuction: false,
  },
];

export function generateAuctions(): AuctionListing[] {
  const n = new Date();
  const auctions: AuctionListing[] = [
    {
      id: 'auction1',
      carId: 'acar1',
      car: {
        id: 'acar1',
        sellerId: 'user7',
        sellerName: 'Thomas Beaumont',
        title: '1966 Pontiac GTO - The Judge',
        make: 'Pontiac',
        model: 'GTO',
        year: 1966,
        price: 0,
        mileage: 41200,
        condition: 'Excellent',
        fuelType: 'Gasoline',
        transmission: 'Manual',
        bodyStyle: 'Coupe',
        driveType: 'RWD',
        color: 'Red',
        interiorColor: 'Black',
        engine: '389 Tri-Power V8',
        horsepower: 360,
        doors: 2,
        vin: 'VC66PO38900',
        location: 'Atlanta, GA',
        description: 'Numbers matching 389 Tri-Power GTO. One of the original muscle cars. Frame-off restored to concours condition.',
        features: ['Matching Numbers', 'Full Frame-Off Restoration', 'Award Winner'],
        images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'],
        createdAt: new Date(n.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        isAuction: true,
      },
      sellerId: 'user7',
      sellerName: 'Thomas Beaumont',
      startingBid: 55000,
      reservePrice: 90000,
      currentBid: 72500,
      currentBidder: 'David K.',
      bids: [
        { id: 'b1', auctionId: 'auction1', bidderId: 'u1', bidderName: 'David K.', amount: 72500, timestamp: new Date(n.getTime() - 30 * 60 * 1000).toISOString() },
        { id: 'b2', auctionId: 'auction1', bidderId: 'u2', bidderName: 'Sarah M.', amount: 68000, timestamp: new Date(n.getTime() - 60 * 60 * 1000).toISOString() },
        { id: 'b3', auctionId: 'auction1', bidderId: 'u3', bidderName: 'Robert T.', amount: 62000, timestamp: new Date(n.getTime() - 90 * 60 * 1000).toISOString() },
        { id: 'b4', auctionId: 'auction1', bidderId: 'u1', bidderName: 'David K.', amount: 57000, timestamp: new Date(n.getTime() - 120 * 60 * 1000).toISOString() },
      ],
      startTime: new Date(n.getTime() - 3 * 60 * 60 * 1000).toISOString(),
      endTime: new Date(n.getTime() + 5 * 60 * 60 * 1000 + 23 * 60 * 1000 + 44 * 1000).toISOString(),
      durationHours: 8,
      status: 'live',
      createdAt: new Date(n.getTime() - 3 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'auction2',
      carId: 'acar2',
      car: {
        id: 'acar2',
        sellerId: 'user8',
        sellerName: 'Patricia Weston',
        title: '1957 Mercedes-Benz 300SL Gullwing',
        make: 'Mercedes-Benz',
        model: '300SL',
        year: 1957,
        price: 0,
        mileage: 28400,
        condition: 'Excellent',
        fuelType: 'Gasoline',
        transmission: 'Manual',
        bodyStyle: 'Coupe',
        driveType: 'RWD',
        color: 'Silver',
        interiorColor: 'Red',
        engine: 'M198 Inline-6',
        horsepower: 215,
        doors: 2,
        vin: 'VC57MB30001',
        location: 'Palm Beach, FL',
        description: 'The iconic Gullwing in stunning silver with red interior. Single owner for 40 years. Matching numbers with complete service history.',
        features: ['Matching Numbers', 'Documented History', 'Original Interior', 'Show Car'],
        images: ['https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=800&q=80'],
        createdAt: new Date(n.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        isAuction: true,
      },
      sellerId: 'user8',
      sellerName: 'Patricia Weston',
      startingBid: 800000,
      reservePrice: 1200000,
      currentBid: 950000,
      currentBidder: 'Anonymous',
      bids: [
        { id: 'b5', auctionId: 'auction2', bidderId: 'u4', bidderName: 'Anonymous', amount: 950000, timestamp: new Date(n.getTime() - 15 * 60 * 1000).toISOString() },
        { id: 'b6', auctionId: 'auction2', bidderId: 'u5', bidderName: 'J. Hartley', amount: 880000, timestamp: new Date(n.getTime() - 45 * 60 * 1000).toISOString() },
      ],
      startTime: new Date(n.getTime() - 2 * 60 * 60 * 1000).toISOString(),
      endTime: new Date(n.getTime() + 10 * 60 * 60 * 1000 + 44 * 60 * 1000 + 12 * 1000).toISOString(),
      durationHours: 12,
      status: 'live',
      createdAt: new Date(n.getTime() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'auction3',
      carId: 'acar3',
      car: {
        id: 'acar3',
        sellerId: 'user9',
        sellerName: 'George Aldrich',
        title: '1955 Chevrolet Nomad Station Wagon',
        make: 'Chevrolet',
        model: 'Nomad',
        year: 1955,
        price: 0,
        mileage: 72000,
        condition: 'Restored',
        fuelType: 'Gasoline',
        transmission: 'Automatic',
        bodyStyle: 'Wagon',
        driveType: 'RWD',
        color: 'Two-Tone',
        interiorColor: 'Turquoise',
        engine: '265 V8',
        horsepower: 180,
        doors: 4,
        vin: 'VC55CN55555',
        location: 'Denver, CO',
        description: 'The legendary 1955 Nomad in beautiful two-tone restoration. One of the most collectible wagons of all time.',
        features: ['Full Frame-Off Restoration', 'Original Paint', 'Chrome Bumpers', 'Whitewall Tires'],
        images: ['https://images.unsplash.com/photo-1471479917193-f00955256257?w=800&q=80'],
        createdAt: new Date(n.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        isAuction: true,
      },
      sellerId: 'user9',
      sellerName: 'George Aldrich',
      startingBid: 40000,
      reservePrice: 65000,
      currentBid: 48500,
      currentBidder: 'Classic Fan',
      bids: [
        { id: 'b7', auctionId: 'auction3', bidderId: 'u6', bidderName: 'Classic Fan', amount: 48500, timestamp: new Date(n.getTime() - 2 * 60 * 60 * 1000).toISOString() },
      ],
      startTime: new Date(n.getTime() + 2 * 60 * 60 * 1000).toISOString(),
      endTime: new Date(n.getTime() + 8 * 60 * 60 * 1000).toISOString(),
      durationHours: 6,
      status: 'upcoming',
      createdAt: new Date(n.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ];
  return auctions;
}
